# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grpc_def/grpc_route.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19grpc_def/grpc_route.proto\x12\ngrpc_route\"*\n\x05Point\x12\r\n\x05maths\x18\x01 \x01(\x05\x12\x12\n\ntiterature\x18\x02 \x01(\x05\" \n\x08\x43\x61tegory\x12\x14\n\x0c\x63\x61tegoryType\x18\x01 \x01(\t2E\n\tGrpcRoute\x12\x38\n\x0bGetCategory\x12\x11.grpc_route.Point\x1a\x14.grpc_route.Category\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'grpc_def.grpc_route_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_POINT']._serialized_start=41
  _globals['_POINT']._serialized_end=83
  _globals['_CATEGORY']._serialized_start=85
  _globals['_CATEGORY']._serialized_end=117
  _globals['_GRPCROUTE']._serialized_start=119
  _globals['_GRPCROUTE']._serialized_end=188
# @@protoc_insertion_point(module_scope)
