# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from grpc_def import grpc_route_pb2 as grpc__def_dot_grpc__route__pb2


class GrpcRouteStub(object):
    """Interface exported by the server.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetCategory = channel.unary_unary(
                '/grpc_route.GrpcRoute/GetCategory',
                request_serializer=grpc__def_dot_grpc__route__pb2.Point.SerializeToString,
                response_deserializer=grpc__def_dot_grpc__route__pb2.Category.FromString,
                )


class GrpcRouteServicer(object):
    """Interface exported by the server.
    """

    def GetCategory(self, request, context):
        """A simple RPC.

        Obtains the category type from a given set of subjects.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GrpcRouteServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetCategory': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCategory,
                    request_deserializer=grpc__def_dot_grpc__route__pb2.Point.FromString,
                    response_serializer=grpc__def_dot_grpc__route__pb2.Category.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'grpc_route.GrpcRoute', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class GrpcRoute(object):
    """Interface exported by the server.
    """

    @staticmethod
    def GetCategory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/grpc_route.GrpcRoute/GetCategory',
            grpc__def_dot_grpc__route__pb2.Point.SerializeToString,
            grpc__def_dot_grpc__route__pb2.Category.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
